BookStore/Models/Book.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace BookStore.Models
{
    public class Book
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        //public string ImageUrl { get; set; } غير اللغه ok
        [ForeignKey("Author")]
        public int AuthorId { get; set; }

        public virtual Author Author { get; set; }

    }
}

BookStore/Controllers/BookController.cs
using BookStore.Models;
using BookStore.Models.Repositories;
using BookStore.ViewModels;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BookStore.Controllers
{
    public class BookController : Controller
    {
        private readonly IBookstoreRepository<Book> bookRepository;
        private readonly IBookstoreRepository<Author> authorRepository;
        //private readonly IHostingEnvironment hosting;

        public BookController(IBookstoreRepository<Book> bookRepository ,IBookstoreRepository<Author> authorRepository)
          
        {
           this.bookRepository = bookRepository;
               this.authorRepository = authorRepository;
        //    this.hosting = hosting;
        }
        // GET: BookController1
        public ActionResult Index()
        {
            var books = bookRepository.list();
            return View(books);
        }

        // GET: BookController1/Details/5
        public ActionResult Details(int id)
        {
            var book = bookRepository.Find(id);
            return View(book);
        }

        // GET: BookController1/Create
        public ActionResult Create()
        {
            var model = new BookAuthorViewModel()
            {
                Authors = FillSelectList()
            };

            return View(model);
        }

        // POST: BookController1/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(BookAuthorViewModel model)
        { 
            if(ModelState.IsValid)
            {
                try
                {
                    //if(model.File != null)
                    //{




                    //}
                    if(model.AuthorId == -1)
                    {
                        ViewBag.Message = "Plase Select An Auhtor from List";
                        var vmodel = new BookAuthorViewModel()
                        {
                            Authors = FillSelectList()
                        };

                        return View(vmodel);
                    }

                    var author = authorRepository.Find(model.AuthorId);
                    Book book = new Book
                    {
                        Id = model.BookId,
                        Title = model.Title,
                        Description = model.Description,
                        Author = author

                    };
                    bookRepository.add(book);
                    return RedirectToAction(nameof(Index));
                }
                catch
                {
                    return View();
                }
            }
            ModelState.AddModelError("", "Yuo Must Fill all Fieds");
            return View();
           
        }

        // GET: BookController1/Edit/5
        public ActionResult Edit(int id)
        {
            var book = bookRepository.Find(id);
            //ViewBag.Authors = authorRepository.list();
            //var authorId = book.Author == null ? book.Author.Id = 0 : book.Author.Id;
            var viewModel = new BookAuthorViewModel
            {
                BookId = book.Id,
                Title = book.Title,
                Description = book.Description,
                Authors = authorRepository.list().ToList(),


        };
            return View(viewModel);
        }

        // POST: BookController1/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit( BookAuthorViewModel viewModel)
        {
            try
            {
                var author = authorRepository.Find(viewModel.AuthorId);
                Book book = new Book
                {
                    Id = viewModel.BookId,
                    Title = viewModel.Title,
                    Description = viewModel.Description,
                    Author = author

                };
                bookRepository.Update(viewModel.BookId, book);

                return RedirectToAction(nameof(Index));
            }

            catch
            {
                return View();
            }
        }

        // GET: BookController1/Delete/5
        public ActionResult Delete(int id)
        {
            var book = bookRepository.Find(id);
            return View(book);
        }

        // POST: BookController1/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        //[Route("Delete")]
        public ActionResult ConfirmDelete(int id)
        {
            try
            {
                bookRepository.Delete(id);
                
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
        List<Author> FillSelectList()
        {
            var authors = authorRepository.list().ToList();
            authors.Insert(0, new Author { Id = -1, FullName = "------Please Select an Author ------" });
            return authors;
        }
        public ActionResult Search(string term)
        {
            var result = bookRepository.Search(term);
            return View("Index", result);
        }
    }
}

BookStore/Views/Book/Create.cshtml
@model BookStore.ViewModels.BookAuthorViewModel

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>BookAuthorViewModel</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            @if (ViewBag.Message != null)
            {
                <h5 class="alert alert-danger">@ViewBag.Message</h5>
            }
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            @*<div class="form-group">
                <label asp-for="BookId" class="control-label"></label>
                <input asp-for="BookId" class="form-control" />
                <span asp-validation-for="BookId" class="text-danger"></span>
            </div>*@
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            @*<div class="form-group">
            <label asp-for="File" class="control-label"></label>
            <input type="file" asp-for="File" class="form-control" />
            <span asp-validation-for="Description" class="text-danger"></span>
    </div>*@
    <div class="form-group">
        <label asp-for="AuthorId" class="control-label"></label>
        <select asp-for="AuthorId" class="form-control"
                asp-items="@(new SelectList(Model.Authors,"Id","FullName"))">
        </select>
        <span asp-validation-for="AuthorId" class="text-danger"></span>
    </div>
    <div class="form-group">
        <input type="submit" value="Create" class="btn btn-primary" />
        <a asp-action="Index" class="btn btn-info">Back</a>
    </div>
    </form>
</div>
</div>



@section Scripts {
    <partial name="_Validation" />
}

BookStore/Views/Book/Delete.cshtml
@model BookStore.Models.Book

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Delete Book</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
    </dl>
    
    <form asp-action="ConfirmDelete" asp-route-id="@Model.Id">
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index" class="btn btn-outline-danger">
            Back
            <i class="fas fa-sign-out-alt"></i>
        </a>
    </form>
</div>

BookStore/Views/Book/Details.cshtml
@model BookStore.Models.Book

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Book</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
    </dl>
</div>
<div>
    @*@Html.ActionLink("Edit", "Edit", new { /* id = Model.PrimaryKey */ }) |
        <a asp-action="Index">Back to List</a>*@
    <a asp-action="Edit" class="btn btn-info" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index" class="btn btn-primary">
        Back
        <i class="fas fa-sign-out-alt"></i>
    </a>

</div>

BookStore/Views/Book/Edit.cshtml
@model BookStore.ViewModels.BookAuthorViewModel

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit Book</h1>

<h4>BookAuthorViewModel</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="BookId" class="control-label"></label>
                <input asp-for="BookId" readonly class="form-control" />
                <span asp-validation-for="BookId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AuthorId" class="control-label"></label>
                <select asp-for="AuthorId" class="form-control"
                        asp-items="@(new SelectList(Model.Authors,"Id","FullName"))">
                </select>
                <span asp-validation-for="AuthorId" class="text-danger"></span>
            </div>
            @*<div class="form-group">
            <label asp-for="AuthorId" class="control-label"></label>
            <input asp-for="AuthorId" class="form-control" />
            <span asp-validation-for="AuthorId" class="text-danger"></span>
        </div>*@
        <div class="form-group">
            <input type="submit" value="Save" class="btn btn-primary" />
            <a asp-action="Index" class="btn btn-danger">
                Back
                <i class="fas fa-sign-out-alt"></i>
            </a>
        </div>
        </form>
    </div>
</div>



@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

BookStore/Views/Book/Index.cshtml
@model IEnumerable<BookStore.Models.Book>

@{
    ViewData["Title"] = "Index";
}

<div class="row pt-4">
    <div class="col-6">
        <h1>List of Books</h1>
    </div>

    <div class="col-6 text-right">
        <p>
            <a class="btn btn-primary" w-100 asp-action="Create">
                <i class="fas fa-plus"></i> &nbsp;  Add New Book
            </a>
        </p>
    </div>
</div>

<table class="table table-bordered table-striped" style="width:100%">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Title)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Author.FullName)
            </th>
            <td></td>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Title)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Author.FullName)
            </td>
            <td>
                <a asp-controller="Book" asp-route-Id="@item.Id" asp-action="Edit" class="btn btn-primary">
                    <i class="fas fa-marker"></i>
                </a>
                <a asp-controller="Book" asp-route-Id="@item.Id" asp-action="Details" class="btn btn-info">
                    <i class="fas fa-info"></i>
                </a>
                <a asp-controller="Book" asp-route-Id="@item.Id" asp-action="Delete" class="btn btn-danger">
                    <i class="fas fa-trash-alt"></i>
                </a>
                @*@Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
            @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
            @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })*@
            </td>
        </tr>
}
    </tbody>
</table>