BookStore/Models/Author.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BookStore.Models
{
    public class Author
    {
        public int Id { get; set; }
        public string FullName { get; set; }
    }
}

BookStore/Controllers/AuthorController.cs
using BookStore.Models;
using BookStore.Models.Repositories;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BookStore.Controllers
{
    public class AuthorController : Controller
    {
        private readonly IBookstoreRepository<Author> authorRepository;

        public AuthorController(IBookstoreRepository<Author> authorRepository)
        {
            this.authorRepository = authorRepository;
        }
        // GET: AuthorController1
        public ActionResult Index()
        {
            var authors = authorRepository.list();
            return View(authors);
        }

        // GET: AuthorController1/Details/5
        public ActionResult Details(int id)
        {
            var author = authorRepository.Find(id);
            return View(author);
        }

        // GET: AuthorController1/Create
        //Diplay the Form enter Data
        public ActionResult Create()
        {
            return View();
        }

        // POST: AuthorController1/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Author author)
        {
            try
            {
                authorRepository.add(author);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: AuthorController1/Edit/5
        public ActionResult Edit(int id)
        {
            var author = authorRepository.Find(id);
            return View(author);
        }

        // POST: AuthorController1/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, Author author)
        {
            try
            {
                authorRepository.Update(id, author);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: AuthorController1/Delete/5
        public ActionResult Delete(int id)
        {
            var author = authorRepository.Find(id);
            return View(author);
        }

        // POST: AuthorController1/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, Author author)
        {
            try
            {
                authorRepository.Delete(id);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

BookStore/Views/Author/Create.cshtml
@model BookStore.Models.Author

@{
    ViewData["Title"] = "Create";
}

<h1>Create New Author</h1>


<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Id" class="control-label"></label>
                <input asp-for="Id" readonly class="form-control" />
                <span asp-validation-for="Id" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FullName" class="control-label"></label>
                <input asp-for="FullName" class="form-control" />
                <span asp-validation-for="FullName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
                <a asp-action="Index" class="btn btn-info">
                    Back
                    <i class="fas fa-sign-out-alt"></i>
                </a>
            </div>
        </form>
    </div>
</div>




@*@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}*@

BookStore/Views/Author/Delete.cshtml
@model BookStore.Models.Author

@{
    ViewData["Title"] = "Delete";
}

<h1 class="text-primary">Delete Author</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Author</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FullName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FullName)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index" class="btn btn-info">
            Back
            <i class="fas fa-sign-out-alt"></i>
        </a>
    </form>
</div>

BookStore/Views/Author/Details.cshtml
@model BookStore.Models.Author

@{
    ViewData["Title"] = "Details";
}

<h1>Author Details</h1>



    <hr />
        <dl class="row">
            <dt class = "col-sm-2">
                @Html.DisplayNameFor(model => model.Id)
            </dt>
            <dd class = "col-sm-10">
                @Html.DisplayFor(model => model.Id)
            </dd>
            <dt class = "col-sm-2">
                @Html.DisplayNameFor(model => model.FullName)
            </dt>
            <dd class = "col-sm-10">
                @Html.DisplayFor(model => model.FullName)
            </dd>
        </dl>

<div>

    <a asp-action="Edit" class="btn btn-info" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index" class="btn btn-primary">
        Back
        <i class="fas fa-sign-out-alt"></i>
    </a>

</div>

BookStore/Views/Author/Edit.cshtml
@model BookStore.Models.Author

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit Author</h1>


<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Id" class="control-label"></label>
                <input asp-for="Id" readonly class="form-control" />
                <span asp-validation-for="Id" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FullName" class="control-label"></label>
                <input asp-for="FullName" class="form-control" />
                <span asp-validation-for="FullName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
               
                <a asp-action="Index" class="btn btn-info">
                    Back
                    <i class="fas fa-sign-out-alt"></i>
                </a>

            </div>
        </form>
    </div>
</div>


@*@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}*@

BookStore/Views/Author/Index.cshtml
@model IEnumerable<BookStore.Models.Author>

@{
    ViewData["Title"] = "Index";
}

<div class="row pt-4">
    <div class="col-6" >
        <h1>List of Authors</h1>
    </div>

    <div class="col-6 text-right">
        <p>
            <a class="btn btn-primary" w-100 asp-action="Create">
                <i class="fas fa-plus"></i> &nbsp;  Create New Author
            </a>
        </p>
    </div>
</div>
<table class="table table-bordered table-striped" style="width:100%">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FullName)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FullName)
            </td>
            <td class="text-center">
                <a asp-controller="Author" asp-route-Id="@item.Id" asp-action="Edit" class="btn btn-primary">
                    <i class="fas fa-marker"></i>
                </a>
                <a asp-controller="Author" asp-route-Id="@item.Id" asp-action="Details" class="btn btn-info">
                    <i class="fas fa-info"></i>
                </a>
                <a asp-controller="Author" asp-route-Id="@item.Id" asp-action="Delete" class="btn btn-danger">
                    <i class="fas fa-trash-alt"></i>
                </a>
                @*@Html.ActionLink("", "Edit", new { id = item.Id })<i class="fas fa-edit"></i> |
                @Html.ActionLink("Details", "Details", new { id = item.Id }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.Id })*@

            </td>
        </tr>
}
    </tbody>
</table>